"""
--- test_included_excluded_chromosomes_beds.py ---

Test the rule included_excluded_chromosomes_beds.smk

Authors:
    - Cameron Fraser
    - Joshua Johnstone
"""

from definitions.paths.io import shared as S
from helpers.get_metadata import load_config

# Ensure the exclude BED file generated by the included_excluded_chromosomes_beds rule 
# does NOT contain chromosomes defined as included_chromosomes in test config.
def test_no_included_chromosomes_in_mask(lightweight_test_run, output_bed_path = S.EXCLUDED_CHROMS_BED):

    config = load_config(lightweight_test_run["test_config_path"])
    included_chromosomes = config["sci_params"]["shared"]["included_chromosomes"]

    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom not in included_chromosomes, f"Found included chromosome {chrom} in excluded chromosomes BED"

# Ensure the include BED file generated by the included_excluded_chromosomes_beds rule 
# contains ONLY chromosomes defined as included_chromosomes in test config.
def test_no_included_chromosomes_in_mask(lightweight_test_run, output_bed_path = S.INCLUDED_CHROMS_BED):

    config = load_config(lightweight_test_run["test_config_path"])
    included_chromosomes = config["sci_params"]["shared"]["included_chromosomes"]

    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom in included_chromosomes, f"Found excluded chromosome {chrom} in included chromosomes BED"
