"""
--- test_create_metrics_report.py ---

Test the component and system level metrics reports, generated by create_metrics_report.R

Authors:
    - Cameron Fraser
"""

# -------------------------------------------------------------------------------------
# Imports
# -------------------------------------------------------------------------------------
from pathlib import Path
import subprocess

import pandas as pd
import pytest

import helpers.get_metadata as md
from conftest import PROJECT_ROOT, TEST_CONFIG

# -------------------------------------------------------------------------------------
# Fixtures
# -------------------------------------------------------------------------------------
@pytest.fixture(scope="module")
def config(lightweight_test_run):
    return md.load_config(lightweight_test_run["test_config_path"])


@pytest.fixture(scope="module", params=["component", "system"])
def metrics_df(request):
    """Load either the component or system metrics report."""
    report_map = {
        "component": Path("metrics") / "component_metrics_report.csv",
        "system": Path("results") / "system_metrics_report.csv",
    }
    df = pd.read_csv(report_map[request.param])
    df["report_type"] = request.param
    return df

# -------------------------------------------------------------------------------------
# Shared tests (run for both reports)
# -------------------------------------------------------------------------------------
def test_expected_metrics_present(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]
    reported = set(
        metrics_df["Metric"]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    manifest_key = "component_metrics_metadata" if report_type == "component" else "system_metrics_metadata"
    expected_manifest = (
        Path(PROJECT_ROOT)
        / TEST_CONFIG["sci_params"]["metrics_manifests"][manifest_key]
    )
    expected_df = pd.read_excel(expected_manifest)

    expected = set(
        expected_df.loc[
            expected_df["include_automated_report"].fillna(False), "Name"
        ]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    missing = sorted(expected - reported)
    assert not missing, (
        f"[{report_type}] Missing metrics (expected but not found): {missing}"
    )


def test_value_all_numeric_no_na(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]

    assert metrics_df["Value"].notna().all(), (
        f"[{report_type}] Found NA in Value column"
    )
    assert pd.api.types.is_numeric_dtype(metrics_df["Value"]), (
        f"[{report_type}] Value column is not numeric dtype "
        f"(got {metrics_df['Value'].dtype})"
    )


def test_grade_no_missing(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]

    assert metrics_df["Grade"].notna().all(), (
        f"[{report_type}] Found missing values in Grade column"
    )

# -------------------------------------------------------------------------------------
# Component-only tests
# -------------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "id_type,getter",
    [
        ("ex_sample", md.get_ex_sample_ids),
        ("ms_sample", md.get_ms_sample_ids),
        ("ex_lane", md.get_ex_lane_ids),
    ],
)
def test_component_uniformity(lightweight_test_run, config, id_type, getter):
    """Ensure all component-level samples/lanes have uniform metric counts."""
    metrics_path = Path("metrics") / "component_metrics_report.csv"
    df = pd.read_csv(metrics_path)

    sample_ids = getter(config)
    sub_df = df[df["Sample"].isin(sample_ids)]
    counts = sub_df["Sample"].value_counts()

    assert len(set(counts)) == 1, (
        f"[component] {id_type}s have unequal counts: {counts.to_dict()}"
    )


@pytest.mark.parametrize("ex_lanes", [["LN001"], ["LN001", "LN002"]])
def test_lane_id_not_split(lightweight_test_run, config, tmp_path, ex_lanes):
    component_metrics_metadata = config["sci_params"]["metrics_manifests"]["component_metrics_metadata"]
    system_metrics_metadata = config["sci_params"]["metrics_manifests"]["system_metrics_metadata"]
    ex_samples = md.get_ex_sample_ids(config)
    ms_samples = md.get_ms_sample_ids(config)

    component_csv = tmp_path / "component_metrics.csv"
    component_png = tmp_path / "component_metrics.png"
    system_csv = tmp_path / "system_metrics.csv"
    system_png = tmp_path / "system_metrics.png"
    log = tmp_path / "create_metrics_report.log"

    subprocess.run(
        [
            "Rscript",
            "rule_scripts/shared/metrics/create_metrics_report.R",
            "--component_metrics_metadata", str(component_metrics_metadata),
            "--system_metrics_metadata", str(system_metrics_metadata),
            "--component_csv", str(component_csv),
            "--component_png", str(component_png),
            "--system_csv", str(system_csv),
            "--system_png", str(system_png),
            "--ex_lanes", *ex_lanes,
            "--ex_samples", *ex_samples,
            "--ms_samples", *ms_samples,
            "--log",
            str(log),
        ],
        check=True,
    )

    component_metrics_report_df = pd.read_csv(component_csv)
    sample_values = component_metrics_report_df["Sample"].unique()
    expected_sample_names = set(ex_lanes) | set(ex_samples) | set(ms_samples)

    for value in sample_values:
        assert value in expected_sample_names, f"Unexpected sample value: {value}"
    