"""
--- test metrics report.py ---

Test the component and system level metrics reports, generated by metrics_reports.R

Authors:
    - Chat-GPT
    - Cameron Fraser
"""

# Import libraries
import pytest
import pandas as pd
from pathlib import Path
import helpers.get_metadata as md

# -------------------------------------------------------------------------------------
# Fixtures
# -------------------------------------------------------------------------------------

@pytest.fixture(scope="module")
def config(lightweight_test_run):
    return md.load_config(lightweight_test_run["test_config_path"])

@pytest.fixture(scope="module", params=["component", "system"])
def metrics_df(request):
    """Load either the component or system metrics report."""
    metrics_dir = Path("metrics")
    results_dir = Path("results")
    report_map = {
        "component": metrics_dir / "component_metrics_report.csv",
        "system": results_dir / "system_metrics_report.csv",
    }
    df = pd.read_csv(report_map[request.param])
    df["report_type"] = request.param
    return df

# -------------------------------------------------------------------------------------
# Shared Tests (run for both reports)
# -------------------------------------------------------------------------------------

def test_expected_metrics_present(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]
    reported = set(
        metrics_df["Metric"]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    # Load expected metrics for this report
    if report_type == "component":
        expected_df = pd.read_excel(Path("config") / "component_level_metrics.xlsx")
    else:
        expected_df = pd.read_excel(Path("config") / "system_level_metrics.xlsx")

    expected = set(
        expected_df.loc[
            expected_df["include_automated_report"].fillna(False), "Name"
        ]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    missing = sorted(expected - reported)
    assert not missing, f"[{report_type}] Missing metrics (expected but not found): {missing}"

def test_value_all_numeric_no_na(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]

    # Value should be present and numeric
    assert metrics_df["Value"].notna().all(), f"[{report_type}] Found NA in Value column"
    assert pd.api.types.is_numeric_dtype(metrics_df["Value"]), (
        f"[{report_type}] Value column is not numeric dtype (got {metrics_df['Value'].dtype})"
    )

def test_grade_no_missing(lightweight_test_run, metrics_df):
    report_type = metrics_df["report_type"].iloc[0]

    # Grade should not contain missing values (NaN/None)
    assert metrics_df["Grade"].notna().all(), f"[{report_type}] Found missing values in Grade column"

# -------------------------------------------------------------------------------------
# Component-only tests
# -------------------------------------------------------------------------------------

@pytest.mark.parametrize("id_type,getter", [
    ("ex_sample", md.get_ex_sample_ids),
    ("ms_sample", md.get_ms_sample_ids),
    ("ex_lane",   md.get_ex_lane_ids),
])
def test_component_uniformity(lightweight_test_run, config, id_type, getter):
    """Ensure all component-level samples/lanes have uniform metric counts."""
    metrics_path = Path("metrics/component_metrics_report.csv")
    df = pd.read_csv(metrics_path)

    sample_ids = getter(config)
    sub_df = df[df["Sample"].isin(sample_ids)]
    counts = sub_df["Sample"].value_counts()

    assert len(set(counts)) == 1, (
        f"[component] {id_type}s have unequal counts: {counts.to_dict()}"
    )