"""
--- test_mask_canonical_chroms.py ---

Test the rule mask_canonical_chroms

Authors:
    - Chat-GPT
    - Cameron Fraser
"""
# Import libraries
import pytest

# Canonical chromosomes in UCSC naming
CANONICAL_CHROMS = {f"chr{i}" for i in range(1, 23)} | {"chrX", "chrY"}

def test_no_canonical_chroms_in_mask(output_bed_path="tmp/downloads/noncanonical_mask.bed"):
    """
    Ensure the BED file generated by the mask_noncanonical_chroms rule
    does NOT contain any canonical chromosomes.
    """
    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom not in CANONICAL_CHROMS, f"Found canonical chrom in mask: {chrom}"
