"""
--- test_mask_non_variant_calling_chroms.py ---

Test the rule mask_non_variant_calling_chroms

Authors:
    - Chat-GPT
    - Cameron Fraser
    - Joshua Johnstone
"""
# Import libraries
import pytest
import sys
from pathlib import Path
import scripts.get_metadata as md

project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

config = md.load_config("config/config.yaml")

# Non-variant calling chromosomes in UCSC naming
NON_VARIANT_CALLING_CHROMS = config["chroms"]["variant_calling"]

def test_no_variant_calling_chroms_in_mask(output_bed_path="tmp/downloads/non_variant_calling_chroms.bed"):
    """
    Ensure the BED file generated by the mask_non_variant_calling_chroms rule
    does NOT contain chromosomes defined as variant calling chroms in config.
    """
    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom not in NON_VARIANT_CALLING_CHROMS, f"Found variant-calling chrom in mask: {chrom}"
