"""
--- test_mask_non_variant_calling_chroms.py ---

Test the rule mask_non_variant_calling_chroms

Authors:
    - Chat-GPT
    - Cameron Fraser
    - Joshua Johnstone
"""
# Variant calling chromosomes as defined in test config
variant_calling_chroms = ["chr21"]

# Ensure the BED file generated by the mask_non_variant_calling_chroms rule 
# does NOT contain chromosomes defined as variant calling chroms in test config.
def test_no_variant_calling_chroms_in_mask(lightweight_test_run, output_bed_path="tmp/downloads/non_variant_calling_chroms.bed"):
    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom not in variant_calling_chroms, f"Found variant-calling chrom in mask: {chrom}"
