---
cwd: /work
ref: tmp/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
ex_samples: config/ex_samples.csv
r1start: tmp/reference/ex_r1start.fasta
r2start: tmp/reference/ex_r2start.fasta
r1end: tmp/reference/ex_r1end.fasta
r2end: tmp/reference/ex_r2end.fasta
ncores: 4