---
GRCh38_path: tmp/downloads/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
ex_samples_path: config/ex_samples.csv
ms_samples_path: config/ms_samples.csv
ex_adapters_path: config/ex_adapters.csv
ms_adaptor_1: CTGTCTCTTATACACATCT
ms_adaptor_2: ATGTGTATAAGAGACA