---
# ------------------------------------------------------------------------------ 
# Experiment name
# ------------------------------------------------------------------------------

experiment_name: experiment_1


# ------------------------------------------------------------------------------
# Rule parameters
# ------------------------------------------------------------------------------

ex_annotate_map:
  min_umi_length: 6

ex_call_dsc:
  max_duplex_disagreements: 3
  min_read_pairs: 1
  single_strand_qual: 2

ex_call_somatic_snv:
  max_base_quality: 150
  min_base_quality: 70

ex_filter_dsc:
  min_mapq: 60

ex_filter_fastq:
  min_read_length: 70
  average_quality_threshold: 34
  n_base_limit: 3

ex_map:
  band_width: 100
  gap_extension_penalty: 1
  clipping_penalty: 5
  gap_open_penalty: 6
  matching_score: 1
  mem_max_occurances: 10000
  min_alignment_score_thresh: 30
  min_seed_length: 19
  mismatch_penalty: 4
  reseed_factor: 1.5
  unpaired_read_penalty: 9
  z_dropoff: 100

ex_remap_dsc:
  band_width: 100
  gap_extension_penalty: 1
  clipping_penalty: 5
  gap_open_penalty: 6
  matching_score: 1
  mem_max_occurances: 10000
  min_alignment_score_thresh: 30
  min_seed_length: 19
  mismatch_penalty: 4
  reseed_factor: 1.5
  unpaired_read_penalty: 9
  z_dropoff: 100

ex_trim_fastq:
  max_adapter_errors: 2
  min_adapter_overlap: 8
  r1_cut_start: 3
  r2_cut_start: 3
  r1_cut_end: -9  # Must be negative
  r2_cut_end: -9  # Must be negative
  quality_cutoff: 20

ms_candidate_germ_variants:
  memory_limit_gb: 32

ms_low_depth_mask:
  threshold: 30

ms_trim_fastq:
  adaptor_1: CTGTCTCTTATACACATCT
  adaptor_2: ATGTGTATAAGAGACA


# ------------------------------------------------------------------------------
# File paths
# -------------------------------------------------------------------------------

GRCh38_path: tmp/downloads/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
difficult_regions_path: tmp/downloads/GRCh38_alldifficultregions.bed
common_variants_path: tmp/downloads/gnomad_common_af01_merged.bed
ex_nanoseq_tri_contexts: tmp/downloads/nanoseq_trinucleotide_contexts.csv
ex_samples_path: config/ex_samples.csv
ex_lanes_path: config/ex_lanes.csv
ex_adapters_path: config/ex_adapters.csv
ms_samples_path: config/ms_samples.csv
component_metrics_path: config/component_metrics.csv
