"""
--- test_mask_excluded_chromosomes.py ---

Test the rule mask_excluded_chromosomes

Authors:
    - Chat-GPT
    - Cameron Fraser
    - Joshua Johnstone
"""
# Chromosomes included for variant calling as defined in test config
included_chromosomes = ["chr21"]

# Ensure the BED file generated by the mask_excluded_chromosomes rule 
# does NOT contain chromosomes defined as included_chromosomes in test config.
def test_no_included_chromosomes_in_mask(lightweight_test_run, output_bed_path="tmp/downloads/excluded_chromosomes.bed"):
    with open(output_bed_path) as bed:
        for line in bed:
            chrom = line.strip().split("\t")[0]
            assert chrom not in included_chromosomes, f"Found included chromosome {chrom} in excluded_chromosomes.bed"
