"""
--- candidate_variant_metrics_summary.py ---

Generates a summary file with key candidate variant metrics

To be used with candidate_variant_metrics_summary rule

Authors:
    - Chat-GPT
    - Joshua Johnstone
"""
import pandas as pd
import json

# Initiate logging
sys.stdout = open(snakemake.log[0], "a")
sys.stderr = open(snakemake.log[0], "a")
print("[INFO] Starting candidate_variant_metrics_summary.py")

# Parses fastqc_data.txt into a dictionary of dataframes
def parse_bcftools_stats(file_path):
    sections = {}
    with open(file_path) as f:
        lines = [line.strip() for line in f if line.strip() and not line.startswith('# This')]

    i = 0
    while i < len(lines):
        if lines[i].startswith("#") or not lines[i]:
            i += 1
            continue

        section_key = lines[i].split("\t")[0]
        data = []

        while i < len(lines) and lines[i].startswith(section_key):
            data.append(lines[i].split("\t")[1:])
            i += 1

        if data:
            max_len = max(len(row) for row in data)
            padded_data = [row + [''] * (max_len - len(row)) for row in data]
            sections.setdefault(section_key, pd.DataFrame(padded_data))

    return sections

# Load reference .fai file path
fai_path = snakemake.input.fai

# Load sample name
sample = snakemake.params.sample

# Load metrics files
variant_metrics_path = snakemake.input.variant_metrics
het_hom_ratio_path = snakemake.input.ms_het_hom_ratio

output_json = snakemake.output.summary

# Get each section of bcftools stats output
sections = parse_bcftools_stats(variant_metrics_path)

# Pull out key metrics and output in json
germline_variant_rate = round(int(sections["SN"].loc[sections["SN"][1] == "number of records:", 2].values[0]) / sum(int(line.split()[1]) for line in open(fai_path)), 4)
snv_indel_ratio = round(int(sections["SN"].loc[sections["SN"][1] == "number of SNPs:", 2].values[0]) / int(sections["SN"].loc[sections["SN"][1] == "number of indels:", 2].values[0]), 2)
insertion_deletion_ratio = round(sections["IDD"][sections["IDD"][2].astype(int) > 0][3].astype(int).sum() / sections["IDD"][sections["IDD"][2].astype(int) < 0][3].astype(int).sum(), 2)
MNP_other_variants = int(sections["SN"].loc[sections["SN"][1] == "number of MNPs:", 2].values[0]) + int(sections["SN"].loc[sections["SN"][1] == "number of others:", 2].values[0])
ms_transition_transversion_ratio = round(float(sections["TSTV"].iloc[0][4]), 2)

# Get het hom ratio from ms_het_hom_ratio.txt file (generated by rule ms_het_hom_ratio)
het_hom_ratio = float(open(het_hom_ratio_path).readlines()[1].strip().split("\t")[2])

result = {
"description": (
    "Summary of key candidate variant metrics (see component metrics csv for definitions)"
),
"sample": sample,
"candidiate_variant_metrics_file": variant_metrics_path,
"germline_variant_rate": germline_variant_rate,
"snv_indel_ratio": snv_indel_ratio,
"insertion_deletion_ratio": insertion_deletion_ratio,
"MNP_other_variants": MNP_other_variants,
"ms_transition_transversion_ratio": ms_transition_transversion_ratio,
"het_hom_ratio": het_hom_ratio
}

with open(output_json, 'w') as f:
    json.dump(result, f, indent=4)

print("[INFO] Completed candidate_variant_metrics_summary.py")








