"""
--- ms_candidate_variant_metrics_summary.py ---

Generates a summary file with key candidate variant metrics

To be used with ms_candidate_variant_metrics_summary rule

Authors:
    - Chat-GPT
    - Joshua Johnstone
"""
import pandas as pd
import json
from collections import defaultdict
import sys

def main(snakemake):
    # Initiate logging
    sys.stdout = open(snakemake.log[0], "a")
    sys.stderr = open(snakemake.log[0], "a")
    print("[INFO] Starting ms_candidate_variant_metrics_summary.py")

    # Parses fastqc_data.txt into a dictionary of dataframes
    def parse_bcftools_stats(file_path):
        sections = defaultdict(list)

        with open(file_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                section_key = parts[0]
                sections[section_key].append(parts[1:])

        # Convert lists to DataFrames
        for key in sections:
            max_len = max(len(row) for row in sections[key])
            padded_data = [row + [''] * (max_len - len(row)) for row in sections[key]]
            sections[key] = pd.DataFrame(padded_data)

        return sections

    # Load reference .fai file path
    fai_path = snakemake.input.fai

    # Load sample name
    sample = snakemake.params.sample

    # Load metrics files
    variant_metrics_path = snakemake.input.variant_metrics
    het_hom_ratio_path = snakemake.input.ms_het_hom_ratio
    mask_metrics_path = snakemake.input.mask_metrics

    # Define output path
    output_json = snakemake.output.summary

    # Get each section of bcftools stats output
    sections = parse_bcftools_stats(variant_metrics_path)

    # Pull out key metrics and output in json
    
    with open(mask_metrics_path) as f:
        mask_metrics_data = json.load(f)
    frac_over_depth_threshold = 1 - (mask_metrics_data["mask_files"]["lowdepth"]["percentage_of_ref_genome"] / 100)
    germline_variant_rate = round(int(sections["SN"].loc[sections["SN"][1] == "number of records:", 2].values[0]) / (sum(int(line.split()[1]) for line in open(fai_path)) * frac_over_depth_threshold), 4)
    
    snv_indel_ratio = round(int(sections["SN"].loc[sections["SN"][1] == "number of SNPs:", 2].values[0]) / int(sections["SN"].loc[sections["SN"][1] == "number of indels:", 2].values[0]), 2)

    insertion_deletion_ratio = round(sections["IDD"][sections["IDD"][1].astype(int) > 0][2].astype(int).sum() / sections["IDD"][sections["IDD"][1].astype(int) < 0][2].astype(int).sum(), 2)

    MNP_other_variants = int(sections["SN"].loc[sections["SN"][1] == "number of MNPs:", 2].values[0]) + int(sections["SN"].loc[sections["SN"][1] == "number of others:", 2].values[0])

    transition_transversion_ratio = round(float(sections["TSTV"].iloc[0][3]), 2)

    # Get het hom ratio from ms_het_hom_ratio.txt file (generated by rule ms_het_hom_ratio)
    het_hom_ratio = round(float(open(het_hom_ratio_path).readlines()[1].strip().split("\t")[2]), 2)

    result = {
    "description": (
        "Summary of key candidate variant metrics (see component metrics csv for definitions)"
    ),
    "sample": sample,
    "fraction_genome_over_depth_threshold": frac_over_depth_threshold,
    "candidiate_variant_metrics_file": variant_metrics_path,
    "germline_variant_rate": germline_variant_rate,
    "snv_indel_ratio": snv_indel_ratio,
    "insertion_deletion_ratio": insertion_deletion_ratio,
    "MNP_other_variants": MNP_other_variants,
    "transition_transversion_ratio": transition_transversion_ratio,
    "het_hom_ratio": het_hom_ratio
    }

    with open(output_json, 'w') as f:
        json.dump(result, f, indent=4)

    print("[INFO] Completed ms_candidate_variant_metrics_summary.py")

if __name__ == "__main__":
    main(snakemake)