---
# ==============================================================================
# Metadata paths
# ==============================================================================
metadata:

  ex_samples_metadata: tests/data/lightweight_test_run/config/ex_samples.csv
  ex_lanes_metadata: tests/data/lightweight_test_run/config/ex_lanes.csv
  ex_adapters_metadata: tests/data/lightweight_test_run/config/ex_adapters.csv
  ms_samples_metadata: tests/data/lightweight_test_run/config/ms_samples.csv
  download_list: tests/data/lightweight_test_run/config/download_list.csv


# ==============================================================================
# Infrastructure
# ==============================================================================
infrastructure:

  memory: # Memory units are expressed in gigabytes (GB) throughout pipeline
    extra_heavy: 6
    heavy: 6
    moderate: 4
    light: 2
    global_buffer: 0

  threads:
    heavy: 2
    moderate: 2
    light: 1
    global_buffer: 0

  compression:
    gzip_level: 1

  create_run_timeline_plot: # Values used to calculate disk usage (no effect on disk behaviour)
    disk_iops: 8000
    disk_throughput: 2000 # MiB/s
    
  log_system_resource_usage:
      sleep_interval: 60

  random_seed: 123 # For metrics that use random sampling such as ex_variant_call_eligible_disagree_rate